syntax = "proto3";

package accountproto;

option go_package = "/internal/domain/account/accountproto";

service Account {
  rpc Create (CreateRequest) returns (CreateResponse);
  rpc Update (UpdateRequest) returns (UpdateResponse);
  rpc Delete (DeleteRequest) returns (DeleteResponse);
  rpc Read (ReadRequest) returns (ReadResponse);
}


message CreateResponse {
  int32 code = 1;
  string msg = 2;
}
message CreateRequest {
  string username = 1;
  string email = 2;
  string first_name = 4;
  string last_name =5;
  repeated string two_factor = 6;
  string password = 7;
}


message UpdateResponse {
  int32 code = 1;
  string msg = 2;
}
message UpdateRequest {
  string username = 1;
  string email = 2;
  string first_name = 4;
  string last_name =5;
  repeated string two_factor = 6;
  int32 id =7;
  string password = 8;
}

message DeleteResponse {
  int32 code = 1;
  string msg = 2;
}
message DeleteRequest {
  int32 id =8;
}

message User {
    string username = 1;
    string email = 2;
    string first_name = 4;
    string last_name =5;
    repeated string two_factor = 6;
    int32 id =7;
}

message ReadResponse {
  int32 code = 1;
  string msg = 2;
  User Data = 3;
}

message ReadRequest {
    int32 id =8;
}


