// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	request "github.com/sajad-dev/authservice/internal/domain/forgetpassword/dto/gen/request"
	response "github.com/sajad-dev/authservice/internal/domain/forgetpassword/dto/gen/response"
	mock "github.com/stretchr/testify/mock"
)

// ForgetPasswordService is an autogenerated mock type for the ForgetPasswordService type
type ForgetPasswordService struct {
	mock.Mock
}

// Forget provides a mock function with given fields: req
func (_m *ForgetPasswordService) Forget(req request.ForgetRequest) (response.ForgetResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Forget")
	}

	var r0 response.ForgetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.ForgetRequest) (response.ForgetResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.ForgetRequest) response.ForgetResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.ForgetResponse)
	}

	if rf, ok := ret.Get(1).(func(request.ForgetRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reset provides a mock function with given fields: req
func (_m *ForgetPasswordService) Reset(req request.ResetRequest) (response.ResetResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 response.ResetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.ResetRequest) (response.ResetResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.ResetRequest) response.ResetResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.ResetResponse)
	}

	if rf, ok := ret.Get(1).(func(request.ResetRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewForgetPasswordService creates a new instance of ForgetPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForgetPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForgetPasswordService {
	mock := &ForgetPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
