// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	forgetpasswordproto "github.com/sajad-dev/authservice/internal/domain/forgetpassword/forgetpasswordproto"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ForgetPasswordClient is an autogenerated mock type for the ForgetPasswordClient type
type ForgetPasswordClient struct {
	mock.Mock
}

// Forget provides a mock function with given fields: ctx, in, opts
func (_m *ForgetPasswordClient) Forget(ctx context.Context, in *forgetpasswordproto.ForgetRequest, opts ...grpc.CallOption) (*forgetpasswordproto.ForgetResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Forget")
	}

	var r0 *forgetpasswordproto.ForgetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *forgetpasswordproto.ForgetRequest, ...grpc.CallOption) (*forgetpasswordproto.ForgetResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *forgetpasswordproto.ForgetRequest, ...grpc.CallOption) *forgetpasswordproto.ForgetResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*forgetpasswordproto.ForgetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *forgetpasswordproto.ForgetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetGRPC provides a mock function with given fields: ctx, in, opts
func (_m *ForgetPasswordClient) ResetGRPC(ctx context.Context, in *forgetpasswordproto.ResetRequest, opts ...grpc.CallOption) (*forgetpasswordproto.ResetResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ResetGRPC")
	}

	var r0 *forgetpasswordproto.ResetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *forgetpasswordproto.ResetRequest, ...grpc.CallOption) (*forgetpasswordproto.ResetResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *forgetpasswordproto.ResetRequest, ...grpc.CallOption) *forgetpasswordproto.ResetResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*forgetpasswordproto.ResetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *forgetpasswordproto.ResetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewForgetPasswordClient creates a new instance of ForgetPasswordClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForgetPasswordClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForgetPasswordClient {
	mock := &ForgetPasswordClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
