// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeForgetPasswordServer is an autogenerated mock type for the UnsafeForgetPasswordServer type
type UnsafeForgetPasswordServer struct {
	mock.Mock
}

// mustEmbedUnimplementedForgetPasswordServer provides a mock function with no fields
func (_m *UnsafeForgetPasswordServer) mustEmbedUnimplementedForgetPasswordServer() {
	_m.Called()
}

// NewUnsafeForgetPasswordServer creates a new instance of UnsafeForgetPasswordServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeForgetPasswordServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeForgetPasswordServer {
	mock := &UnsafeForgetPasswordServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
