// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	groupproto "github.com/sajad-dev/authservice/authorization/internal/domain/group/groupproto"
	mock "github.com/stretchr/testify/mock"
)

// GroupServer is an autogenerated mock type for the GroupServer type
type GroupServer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *GroupServer) Create(_a0 context.Context, _a1 *groupproto.CreateRequest) (*groupproto.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *groupproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.CreateRequest) (*groupproto.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.CreateRequest) *groupproto.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *groupproto.CreateRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *GroupServer) Delete(_a0 context.Context, _a1 *groupproto.DeleteRequest) (*groupproto.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *groupproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.DeleteRequest) (*groupproto.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.DeleteRequest) *groupproto.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *groupproto.DeleteRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: _a0, _a1
func (_m *GroupServer) GetAll(_a0 context.Context, _a1 *groupproto.GetAllRequest) (*groupproto.GetAllResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *groupproto.GetAllResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.GetAllRequest) (*groupproto.GetAllResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.GetAllRequest) *groupproto.GetAllResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupproto.GetAllResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *groupproto.GetAllRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedGroupServer provides a mock function with no fields
func (_m *GroupServer) mustEmbedUnimplementedGroupServer() {
	_m.Called()
}

// NewGroupServer creates a new instance of GroupServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupServer {
	mock := &GroupServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
