// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	groupproto "github.com/sajad-dev/authservice/authorization/internal/domain/group/groupproto"
	mock "github.com/stretchr/testify/mock"
)

// GroupHandler is an autogenerated mock type for the GroupHandler type
type GroupHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *GroupHandler) Create(req *groupproto.CreateRequest) (*groupproto.Response, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *groupproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*groupproto.CreateRequest) (*groupproto.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*groupproto.CreateRequest) *groupproto.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*groupproto.CreateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: req
func (_m *GroupHandler) Delete(req *groupproto.DeleteRequest) (*groupproto.Response, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *groupproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*groupproto.DeleteRequest) (*groupproto.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*groupproto.DeleteRequest) *groupproto.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*groupproto.DeleteRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: req
func (_m *GroupHandler) GetAll(req *groupproto.GetAllRequest) (*groupproto.GetAllResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *groupproto.GetAllResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*groupproto.GetAllRequest) (*groupproto.GetAllResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*groupproto.GetAllRequest) *groupproto.GetAllResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupproto.GetAllResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*groupproto.GetAllRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGroupHandler creates a new instance of GroupHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupHandler {
	mock := &GroupHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
