// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	groupproto "github.com/sajad-dev/authservice/authorization/internal/domain/group/groupproto"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// GroupClient is an autogenerated mock type for the GroupClient type
type GroupClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *GroupClient) Create(ctx context.Context, in *groupproto.CreateRequest, opts ...grpc.CallOption) (*groupproto.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *groupproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.CreateRequest, ...grpc.CallOption) (*groupproto.Response, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.CreateRequest, ...grpc.CallOption) *groupproto.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *groupproto.CreateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, in, opts
func (_m *GroupClient) Delete(ctx context.Context, in *groupproto.DeleteRequest, opts ...grpc.CallOption) (*groupproto.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *groupproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.DeleteRequest, ...grpc.CallOption) (*groupproto.Response, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.DeleteRequest, ...grpc.CallOption) *groupproto.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *groupproto.DeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, in, opts
func (_m *GroupClient) GetAll(ctx context.Context, in *groupproto.GetAllRequest, opts ...grpc.CallOption) (*groupproto.GetAllResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *groupproto.GetAllResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.GetAllRequest, ...grpc.CallOption) (*groupproto.GetAllResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *groupproto.GetAllRequest, ...grpc.CallOption) *groupproto.GetAllResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupproto.GetAllResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *groupproto.GetAllRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGroupClient creates a new instance of GroupClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupClient {
	mock := &GroupClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
