// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeGroupServer is an autogenerated mock type for the UnsafeGroupServer type
type UnsafeGroupServer struct {
	mock.Mock
}

// mustEmbedUnimplementedGroupServer provides a mock function with no fields
func (_m *UnsafeGroupServer) mustEmbedUnimplementedGroupServer() {
	_m.Called()
}

// NewUnsafeGroupServer creates a new instance of UnsafeGroupServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeGroupServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeGroupServer {
	mock := &UnsafeGroupServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
