version: "3.9"

services:
  authorization:
    build:
      context: ./authorization
      dockerfile: Dockerfile
    env_file:
      - ./authorization/.env
    container_name: authorization_service
    networks:
      - app_network
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      # POSTGRES_DB: authorization
    networks:
      - app_network

  envoy:
    image: envoyproxy/envoy:v1.34-latest
    container_name: envoy_proxy
    ports:
      - "8080:8080"
      - "8001:8001"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./envoy/group.pb:/etc/envoy/group.pb:ro 
    depends_on:
      - authorization
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

