// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/sajad-dev/authservice/authentication/internal/shared/models"
	mock "github.com/stretchr/testify/mock"
)

// AccountCURDRepositories is an autogenerated mock type for the AccountCURDRepositories type
type AccountCURDRepositories struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *AccountCURDRepositories) Create(req *models.Accounts) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Accounts) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *AccountCURDRepositories) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: id
func (_m *AccountCURDRepositories) Read(id int) (*models.Accounts, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *models.Accounts
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Accounts, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Accounts); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Accounts)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: req
func (_m *AccountCURDRepositories) Update(req *models.Accounts) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Accounts) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccountCURDRepositories creates a new instance of AccountCURDRepositories. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountCURDRepositories(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountCURDRepositories {
	mock := &AccountCURDRepositories{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
