// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	accountproto "github.com/sajad-dev/authservice/authentication/internal/domain/account/accountproto"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// AccountClient is an autogenerated mock type for the AccountClient type
type AccountClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *AccountClient) Create(ctx context.Context, in *accountproto.CreateRequest, opts ...grpc.CallOption) (*accountproto.CreateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *accountproto.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.CreateRequest, ...grpc.CallOption) (*accountproto.CreateResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.CreateRequest, ...grpc.CallOption) *accountproto.CreateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *accountproto.CreateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, in, opts
func (_m *AccountClient) Delete(ctx context.Context, in *accountproto.DeleteRequest, opts ...grpc.CallOption) (*accountproto.DeleteResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *accountproto.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.DeleteRequest, ...grpc.CallOption) (*accountproto.DeleteResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.DeleteRequest, ...grpc.CallOption) *accountproto.DeleteResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *accountproto.DeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: ctx, in, opts
func (_m *AccountClient) Read(ctx context.Context, in *accountproto.ReadRequest, opts ...grpc.CallOption) (*accountproto.ReadResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *accountproto.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.ReadRequest, ...grpc.CallOption) (*accountproto.ReadResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.ReadRequest, ...grpc.CallOption) *accountproto.ReadResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.ReadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *accountproto.ReadRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, in, opts
func (_m *AccountClient) Update(ctx context.Context, in *accountproto.UpdateRequest, opts ...grpc.CallOption) (*accountproto.UpdateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *accountproto.UpdateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.UpdateRequest, ...grpc.CallOption) (*accountproto.UpdateResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.UpdateRequest, ...grpc.CallOption) *accountproto.UpdateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.UpdateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *accountproto.UpdateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountClient creates a new instance of AccountClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountClient {
	mock := &AccountClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
