// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAccountServer is an autogenerated mock type for the UnsafeAccountServer type
type UnsafeAccountServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAccountServer provides a mock function with no fields
func (_m *UnsafeAccountServer) mustEmbedUnimplementedAccountServer() {
	_m.Called()
}

// NewUnsafeAccountServer creates a new instance of UnsafeAccountServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeAccountServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeAccountServer {
	mock := &UnsafeAccountServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
