// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	request "github.com/sajad-dev/authservice/authentication/internal/domain/twofactor/dto/gen/request"
	response "github.com/sajad-dev/authservice/authentication/internal/domain/twofactor/dto/gen/response"
	mock "github.com/stretchr/testify/mock"
)

// TwoFactorService is an autogenerated mock type for the TwoFactorService type
type TwoFactorService struct {
	mock.Mock
}

// Email provides a mock function with given fields: req
func (_m *TwoFactorService) Email(req request.EmailRequest) (response.TwoFactorResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Email")
	}

	var r0 response.TwoFactorResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.EmailRequest) (response.TwoFactorResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.EmailRequest) response.TwoFactorResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.TwoFactorResponse)
	}

	if rf, ok := ret.Get(1).(func(request.EmailRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Google provides a mock function with given fields: req
func (_m *TwoFactorService) Google(req request.GoogleRequest) (response.TwoFactorResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Google")
	}

	var r0 response.TwoFactorResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.GoogleRequest) (response.TwoFactorResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.GoogleRequest) response.TwoFactorResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.TwoFactorResponse)
	}

	if rf, ok := ret.Get(1).(func(request.GoogleRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTwoFactorService creates a new instance of TwoFactorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTwoFactorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TwoFactorService {
	mock := &TwoFactorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
