// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	twofactorproto "github.com/sajad-dev/authservice/authentication/internal/domain/twofactor/twofactorproto"
	mock "github.com/stretchr/testify/mock"
)

// TwofactoryServer is an autogenerated mock type for the TwofactoryServer type
type TwofactoryServer struct {
	mock.Mock
}

// Email provides a mock function with given fields: _a0, _a1
func (_m *TwofactoryServer) Email(_a0 context.Context, _a1 *twofactorproto.EmailRequest) (*twofactorproto.TwoFactorResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Email")
	}

	var r0 *twofactorproto.TwoFactorResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *twofactorproto.EmailRequest) (*twofactorproto.TwoFactorResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *twofactorproto.EmailRequest) *twofactorproto.TwoFactorResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twofactorproto.TwoFactorResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *twofactorproto.EmailRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Google provides a mock function with given fields: _a0, _a1
func (_m *TwofactoryServer) Google(_a0 context.Context, _a1 *twofactorproto.GoogleRequest) (*twofactorproto.TwoFactorResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Google")
	}

	var r0 *twofactorproto.TwoFactorResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *twofactorproto.GoogleRequest) (*twofactorproto.TwoFactorResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *twofactorproto.GoogleRequest) *twofactorproto.TwoFactorResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twofactorproto.TwoFactorResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *twofactorproto.GoogleRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedTwofactoryServer provides a mock function with no fields
func (_m *TwofactoryServer) mustEmbedUnimplementedTwofactoryServer() {
	_m.Called()
}

// NewTwofactoryServer creates a new instance of TwofactoryServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTwofactoryServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TwofactoryServer {
	mock := &TwofactoryServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
