// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	twofactorproto "github.com/sajad-dev/authservice/authentication/internal/domain/twofactor/twofactorproto"
)

// TwofactoryClient is an autogenerated mock type for the TwofactoryClient type
type TwofactoryClient struct {
	mock.Mock
}

// Email provides a mock function with given fields: ctx, in, opts
func (_m *TwofactoryClient) Email(ctx context.Context, in *twofactorproto.EmailRequest, opts ...grpc.CallOption) (*twofactorproto.TwoFactorResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Email")
	}

	var r0 *twofactorproto.TwoFactorResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *twofactorproto.EmailRequest, ...grpc.CallOption) (*twofactorproto.TwoFactorResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *twofactorproto.EmailRequest, ...grpc.CallOption) *twofactorproto.TwoFactorResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twofactorproto.TwoFactorResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *twofactorproto.EmailRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Google provides a mock function with given fields: ctx, in, opts
func (_m *TwofactoryClient) Google(ctx context.Context, in *twofactorproto.GoogleRequest, opts ...grpc.CallOption) (*twofactorproto.TwoFactorResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Google")
	}

	var r0 *twofactorproto.TwoFactorResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *twofactorproto.GoogleRequest, ...grpc.CallOption) (*twofactorproto.TwoFactorResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *twofactorproto.GoogleRequest, ...grpc.CallOption) *twofactorproto.TwoFactorResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twofactorproto.TwoFactorResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *twofactorproto.GoogleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTwofactoryClient creates a new instance of TwofactoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTwofactoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TwofactoryClient {
	mock := &TwofactoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
