// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/sajad-dev/authservice/authentication/internal/shared/models"
	mock "github.com/stretchr/testify/mock"
)

// TwoFactorRepository is an autogenerated mock type for the TwoFactorRepository type
type TwoFactorRepository struct {
	mock.Mock
}

// FindByCode provides a mock function with given fields: code, codeType
func (_m *TwoFactorRepository) FindByCode(code int, codeType string) ([]*models.TwoFactorCode, error) {
	ret := _m.Called(code, codeType)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 []*models.TwoFactorCode
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) ([]*models.TwoFactorCode, error)); ok {
		return rf(code, codeType)
	}
	if rf, ok := ret.Get(0).(func(int, string) []*models.TwoFactorCode); ok {
		r0 = rf(code, codeType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TwoFactorCode)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(code, codeType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *TwoFactorRepository) FindById(id int) (*models.Accounts, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *models.Accounts
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Accounts, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Accounts); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Accounts)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTwoFactorRepository creates a new instance of TwoFactorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTwoFactorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TwoFactorRepository {
	mock := &TwoFactorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
