// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	request "github.com/sajad-dev/authservice/authorization/internal/domain/policy/dto/gen/request"

	response "github.com/sajad-dev/authservice/authorization/internal/domain/policy/dto/gen/response"
)

// PolicyService is an autogenerated mock type for the PolicyService type
type PolicyService struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *PolicyService) Create(req request.CreateRequest) (response.Response, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 response.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CreateRequest) (response.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.CreateRequest) response.Response); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.Response)
	}

	if rf, ok := ret.Get(1).(func(request.CreateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: req
func (_m *PolicyService) Delete(req request.DeleteRequest) (response.Response, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 response.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(request.DeleteRequest) (response.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.DeleteRequest) response.Response); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.Response)
	}

	if rf, ok := ret.Get(1).(func(request.DeleteRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with no fields
func (_m *PolicyService) GetAll() (response.GetAllResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 response.GetAllResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (response.GetAllResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() response.GetAllResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(response.GetAllResponse)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPolicyService creates a new instance of PolicyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyService {
	mock := &PolicyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
