// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	policyproto "github.com/sajad-dev/authservice/authorization/internal/domain/policy/policyproto"
)

// PolicyHandler is an autogenerated mock type for the PolicyHandler type
type PolicyHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *PolicyHandler) Create(req *policyproto.CreateRequest) (*policyproto.Response, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *policyproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*policyproto.CreateRequest) (*policyproto.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*policyproto.CreateRequest) *policyproto.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*policyproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*policyproto.CreateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: req
func (_m *PolicyHandler) Delete(req *policyproto.DeleteRequest) (*policyproto.Response, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *policyproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*policyproto.DeleteRequest) (*policyproto.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*policyproto.DeleteRequest) *policyproto.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*policyproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*policyproto.DeleteRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: req
func (_m *PolicyHandler) GetAll(req *policyproto.GetAllRequest) (*policyproto.GetAllResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *policyproto.GetAllResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*policyproto.GetAllRequest) (*policyproto.GetAllResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*policyproto.GetAllRequest) *policyproto.GetAllResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*policyproto.GetAllResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*policyproto.GetAllRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPolicyHandler creates a new instance of PolicyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyHandler {
	mock := &PolicyHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
