// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	policyproto "github.com/sajad-dev/authservice/authorization/internal/domain/policy/policyproto"
	mock "github.com/stretchr/testify/mock"
)

// PolicyServer is an autogenerated mock type for the PolicyServer type
type PolicyServer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *PolicyServer) Create(_a0 context.Context, _a1 *policyproto.CreateRequest) (*policyproto.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *policyproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.CreateRequest) (*policyproto.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.CreateRequest) *policyproto.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*policyproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *policyproto.CreateRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *PolicyServer) Delete(_a0 context.Context, _a1 *policyproto.DeleteRequest) (*policyproto.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *policyproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.DeleteRequest) (*policyproto.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.DeleteRequest) *policyproto.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*policyproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *policyproto.DeleteRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: _a0, _a1
func (_m *PolicyServer) GetAll(_a0 context.Context, _a1 *policyproto.GetAllRequest) (*policyproto.GetAllResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *policyproto.GetAllResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.GetAllRequest) (*policyproto.GetAllResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.GetAllRequest) *policyproto.GetAllResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*policyproto.GetAllResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *policyproto.GetAllRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedPolicyServer provides a mock function with no fields
func (_m *PolicyServer) mustEmbedUnimplementedPolicyServer() {
	_m.Called()
}

// NewPolicyServer creates a new instance of PolicyServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyServer {
	mock := &PolicyServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
