// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	policyproto "github.com/sajad-dev/authservice/authorization/internal/domain/policy/policyproto"
)

// PolicyClient is an autogenerated mock type for the PolicyClient type
type PolicyClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *PolicyClient) Create(ctx context.Context, in *policyproto.CreateRequest, opts ...grpc.CallOption) (*policyproto.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *policyproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.CreateRequest, ...grpc.CallOption) (*policyproto.Response, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.CreateRequest, ...grpc.CallOption) *policyproto.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*policyproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *policyproto.CreateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, in, opts
func (_m *PolicyClient) Delete(ctx context.Context, in *policyproto.DeleteRequest, opts ...grpc.CallOption) (*policyproto.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *policyproto.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.DeleteRequest, ...grpc.CallOption) (*policyproto.Response, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.DeleteRequest, ...grpc.CallOption) *policyproto.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*policyproto.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *policyproto.DeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, in, opts
func (_m *PolicyClient) GetAll(ctx context.Context, in *policyproto.GetAllRequest, opts ...grpc.CallOption) (*policyproto.GetAllResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *policyproto.GetAllResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.GetAllRequest, ...grpc.CallOption) (*policyproto.GetAllResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *policyproto.GetAllRequest, ...grpc.CallOption) *policyproto.GetAllResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*policyproto.GetAllResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *policyproto.GetAllRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPolicyClient creates a new instance of PolicyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyClient {
	mock := &PolicyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
