// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafePolicyServer is an autogenerated mock type for the UnsafePolicyServer type
type UnsafePolicyServer struct {
	mock.Mock
}

// mustEmbedUnimplementedPolicyServer provides a mock function with no fields
func (_m *UnsafePolicyServer) mustEmbedUnimplementedPolicyServer() {
	_m.Called()
}

// NewUnsafePolicyServer creates a new instance of UnsafePolicyServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafePolicyServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafePolicyServer {
	mock := &UnsafePolicyServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
