// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/sajad-dev/authservice/authentication/internal/shared/models"
	mock "github.com/stretchr/testify/mock"
)

// ForgetPasswordRepo is an autogenerated mock type for the ForgetPasswordRepo type
type ForgetPasswordRepo struct {
	mock.Mock
}

// Find provides a mock function with given fields: clm, value
func (_m *ForgetPasswordRepo) Find(clm string, value string) (*models.Accounts, error) {
	ret := _m.Called(clm, value)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *models.Accounts
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.Accounts, error)); ok {
		return rf(clm, value)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.Accounts); ok {
		r0 = rf(clm, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Accounts)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clm, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *ForgetPasswordRepo) FindById(id int) (*models.Accounts, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *models.Accounts
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Accounts, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Accounts); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Accounts)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: row
func (_m *ForgetPasswordRepo) Update(row *models.Accounts) error {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Accounts) error); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewForgetPasswordRepo creates a new instance of ForgetPasswordRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForgetPasswordRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForgetPasswordRepo {
	mock := &ForgetPasswordRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
