// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	forgetpasswordproto "github.com/sajad-dev/authservice/authentication/internal/domain/forgetpassword/forgetpasswordproto"
	mock "github.com/stretchr/testify/mock"
)

// ForgetPasswordServer is an autogenerated mock type for the ForgetPasswordServer type
type ForgetPasswordServer struct {
	mock.Mock
}

// Forget provides a mock function with given fields: _a0, _a1
func (_m *ForgetPasswordServer) Forget(_a0 context.Context, _a1 *forgetpasswordproto.ForgetRequest) (*forgetpasswordproto.ForgetResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Forget")
	}

	var r0 *forgetpasswordproto.ForgetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *forgetpasswordproto.ForgetRequest) (*forgetpasswordproto.ForgetResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *forgetpasswordproto.ForgetRequest) *forgetpasswordproto.ForgetResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*forgetpasswordproto.ForgetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *forgetpasswordproto.ForgetRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetGRPC provides a mock function with given fields: _a0, _a1
func (_m *ForgetPasswordServer) ResetGRPC(_a0 context.Context, _a1 *forgetpasswordproto.ResetRequest) (*forgetpasswordproto.ResetResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ResetGRPC")
	}

	var r0 *forgetpasswordproto.ResetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *forgetpasswordproto.ResetRequest) (*forgetpasswordproto.ResetResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *forgetpasswordproto.ResetRequest) *forgetpasswordproto.ResetResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*forgetpasswordproto.ResetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *forgetpasswordproto.ResetRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedForgetPasswordServer provides a mock function with no fields
func (_m *ForgetPasswordServer) mustEmbedUnimplementedForgetPasswordServer() {
	_m.Called()
}

// NewForgetPasswordServer creates a new instance of ForgetPasswordServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForgetPasswordServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForgetPasswordServer {
	mock := &ForgetPasswordServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
