// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	forgetpasswordproto "github.com/sajad-dev/authservice/authentication/internal/domain/forgetpassword/forgetpasswordproto"
	mock "github.com/stretchr/testify/mock"
)

// ForgetPasswordHandler is an autogenerated mock type for the ForgetPasswordHandler type
type ForgetPasswordHandler struct {
	mock.Mock
}

// Forget provides a mock function with given fields: req
func (_m *ForgetPasswordHandler) Forget(req *forgetpasswordproto.ForgetRequest) (*forgetpasswordproto.ForgetResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Forget")
	}

	var r0 *forgetpasswordproto.ForgetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*forgetpasswordproto.ForgetRequest) (*forgetpasswordproto.ForgetResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*forgetpasswordproto.ForgetRequest) *forgetpasswordproto.ForgetResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*forgetpasswordproto.ForgetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*forgetpasswordproto.ForgetRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reset provides a mock function with given fields: req
func (_m *ForgetPasswordHandler) Reset(req *forgetpasswordproto.ResetRequest) (*forgetpasswordproto.ResetResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 *forgetpasswordproto.ResetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*forgetpasswordproto.ResetRequest) (*forgetpasswordproto.ResetResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*forgetpasswordproto.ResetRequest) *forgetpasswordproto.ResetResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*forgetpasswordproto.ResetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*forgetpasswordproto.ResetRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewForgetPasswordHandler creates a new instance of ForgetPasswordHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForgetPasswordHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForgetPasswordHandler {
	mock := &ForgetPasswordHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
