// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/domain/authorization/authorization.proto

package authorizationproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationResponse) Reset() {
	*x = AuthorizationResponse{}
	mi := &file_internal_domain_authorization_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationResponse) ProtoMessage() {}

func (x *AuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_authorization_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_authorization_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthorizationResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Grp           string                 `protobuf:"bytes,2,opt,name=Grp,proto3" json:"Grp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRequest) Reset() {
	*x = GroupRequest{}
	mi := &file_internal_domain_authorization_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequest) ProtoMessage() {}

func (x *GroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_authorization_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequest.ProtoReflect.Descriptor instead.
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_authorization_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *GroupRequest) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *GroupRequest) GetGrp() string {
	if x != nil {
		return x.Grp
	}
	return ""
}

type PolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Obj           string                 `protobuf:"bytes,2,opt,name=obj,proto3" json:"obj,omitempty"`
	Act           string                 `protobuf:"bytes,3,opt,name=act,proto3" json:"act,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRequest) Reset() {
	*x = PolicyRequest{}
	mi := &file_internal_domain_authorization_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRequest) ProtoMessage() {}

func (x *PolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_authorization_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRequest.ProtoReflect.Descriptor instead.
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_authorization_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyRequest) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *PolicyRequest) GetObj() string {
	if x != nil {
		return x.Obj
	}
	return ""
}

func (x *PolicyRequest) GetAct() string {
	if x != nil {
		return x.Act
	}
	return ""
}

var File_internal_domain_authorization_authorization_proto protoreflect.FileDescriptor

const file_internal_domain_authorization_authorization_proto_rawDesc = "" +
	"\n" +
	"1internal/domain/authorization/authorization.proto\x12\x12authorizationproto\"=\n" +
	"\x15AuthorizationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"2\n" +
	"\fGroupRequest\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x10\n" +
	"\x03Grp\x18\x02 \x01(\tR\x03Grp\"E\n" +
	"\rPolicyRequest\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x10\n" +
	"\x03obj\x18\x02 \x01(\tR\x03obj\x12\x10\n" +
	"\x03act\x18\x03 \x01(\tR\x03act2\xbd\x01\n" +
	"\rAuthorization\x12T\n" +
	"\x05Group\x12 .authorizationproto.GroupRequest\x1a).authorizationproto.AuthorizationResponse\x12V\n" +
	"\x06Policy\x12!.authorizationproto.PolicyRequest\x1a).authorizationproto.AuthorizationResponseB3Z1/internal/domain/authorization/authorizationprotob\x06proto3"

var (
	file_internal_domain_authorization_authorization_proto_rawDescOnce sync.Once
	file_internal_domain_authorization_authorization_proto_rawDescData []byte
)

func file_internal_domain_authorization_authorization_proto_rawDescGZIP() []byte {
	file_internal_domain_authorization_authorization_proto_rawDescOnce.Do(func() {
		file_internal_domain_authorization_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_domain_authorization_authorization_proto_rawDesc), len(file_internal_domain_authorization_authorization_proto_rawDesc)))
	})
	return file_internal_domain_authorization_authorization_proto_rawDescData
}

var file_internal_domain_authorization_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_domain_authorization_authorization_proto_goTypes = []any{
	(*AuthorizationResponse)(nil), // 0: authorizationproto.AuthorizationResponse
	(*GroupRequest)(nil),          // 1: authorizationproto.GroupRequest
	(*PolicyRequest)(nil),         // 2: authorizationproto.PolicyRequest
}
var file_internal_domain_authorization_authorization_proto_depIdxs = []int32{
	1, // 0: authorizationproto.Authorization.Group:input_type -> authorizationproto.GroupRequest
	2, // 1: authorizationproto.Authorization.Policy:input_type -> authorizationproto.PolicyRequest
	0, // 2: authorizationproto.Authorization.Group:output_type -> authorizationproto.AuthorizationResponse
	0, // 3: authorizationproto.Authorization.Policy:output_type -> authorizationproto.AuthorizationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_domain_authorization_authorization_proto_init() }
func file_internal_domain_authorization_authorization_proto_init() {
	if File_internal_domain_authorization_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_domain_authorization_authorization_proto_rawDesc), len(file_internal_domain_authorization_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_domain_authorization_authorization_proto_goTypes,
		DependencyIndexes: file_internal_domain_authorization_authorization_proto_depIdxs,
		MessageInfos:      file_internal_domain_authorization_authorization_proto_msgTypes,
	}.Build()
	File_internal_domain_authorization_authorization_proto = out.File
	file_internal_domain_authorization_authorization_proto_goTypes = nil
	file_internal_domain_authorization_authorization_proto_depIdxs = nil
}
