// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/domain/policy/policy.proto

package policyproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_domain_policy_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_policy_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_domain_policy_policy_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRequest) Reset() {
	*x = GroupRequest{}
	mi := &file_internal_domain_policy_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequest) ProtoMessage() {}

func (x *GroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_policy_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequest.ProtoReflect.Descriptor instead.
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_policy_policy_proto_rawDescGZIP(), []int{1}
}

func (x *GroupRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type PolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRequest) Reset() {
	*x = PolicyRequest{}
	mi := &file_internal_domain_policy_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRequest) ProtoMessage() {}

func (x *PolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_policy_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRequest.ProtoReflect.Descriptor instead.
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_policy_policy_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PolicyRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *PolicyRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_internal_domain_policy_policy_proto protoreflect.FileDescriptor

const file_internal_domain_policy_policy_proto_rawDesc = "" +
	"\n" +
	"#internal/domain/policy/policy.proto\x12\vpolicyproto\"8\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\fGroupRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"W\n" +
	"\rPolicyRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action2\x80\x01\n" +
	"\x06Policy\x129\n" +
	"\x05Group\x12\x19.policyproto.GroupRequest\x1a\x15.policyproto.Response\x12;\n" +
	"\x06Policy\x12\x1a.policyproto.PolicyRequest\x1a\x15.policyproto.ResponseB%Z#/internal/domain/policy/policyprotob\x06proto3"

var (
	file_internal_domain_policy_policy_proto_rawDescOnce sync.Once
	file_internal_domain_policy_policy_proto_rawDescData []byte
)

func file_internal_domain_policy_policy_proto_rawDescGZIP() []byte {
	file_internal_domain_policy_policy_proto_rawDescOnce.Do(func() {
		file_internal_domain_policy_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_domain_policy_policy_proto_rawDesc), len(file_internal_domain_policy_policy_proto_rawDesc)))
	})
	return file_internal_domain_policy_policy_proto_rawDescData
}

var file_internal_domain_policy_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_domain_policy_policy_proto_goTypes = []any{
	(*Response)(nil),      // 0: policyproto.Response
	(*GroupRequest)(nil),  // 1: policyproto.GroupRequest
	(*PolicyRequest)(nil), // 2: policyproto.PolicyRequest
}
var file_internal_domain_policy_policy_proto_depIdxs = []int32{
	1, // 0: policyproto.Policy.Group:input_type -> policyproto.GroupRequest
	2, // 1: policyproto.Policy.Policy:input_type -> policyproto.PolicyRequest
	0, // 2: policyproto.Policy.Group:output_type -> policyproto.Response
	0, // 3: policyproto.Policy.Policy:output_type -> policyproto.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_domain_policy_policy_proto_init() }
func file_internal_domain_policy_policy_proto_init() {
	if File_internal_domain_policy_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_domain_policy_policy_proto_rawDesc), len(file_internal_domain_policy_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_domain_policy_policy_proto_goTypes,
		DependencyIndexes: file_internal_domain_policy_policy_proto_depIdxs,
		MessageInfos:      file_internal_domain_policy_policy_proto_msgTypes,
	}.Build()
	File_internal_domain_policy_policy_proto = out.File
	file_internal_domain_policy_policy_proto_goTypes = nil
	file_internal_domain_policy_policy_proto_depIdxs = nil
}
