version: "3.9"

services:
  xds:
    build:
      context: ./xds
      dockerfile: Dockerfile
    container_name: xds
    networks:
      - app_network
    restart: unless-stopped
    ports:
      - "8082:8082"


  envoy:
    image: envoyproxy/envoy:v1.34-latest
    container_name: envoy_proxy
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - xds
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

