syntax = "proto3";

package twofactorproto;

import "google/api/annotations.proto";

option go_package = "/internal/domain/twofactor/twofactorproto";

service Twofactor {
  rpc Email (EmailRequest) returns (TwoFactorResponse) {
    option (google.api.http) = {
      post: "/twofactor/email"
      body: "*"
    };
  }

  rpc Google (GoogleRequest) returns (TwoFactorResponse) {
    option (google.api.http) = {
      post: "/twofactor/google"
      body: "*"
    };
  }
}


message User {
  string username = 1;
  string email = 2;
  string first_name = 4;
  string last_name =5;
  repeated string two_factor = 6;
  int32 id =7;

}

message TwoFactorResponse {
  int32 code = 1;
  string msg = 2;
  User data = 3;
  string token = 4;

}

message EmailRequest {
      int32 code = 1;
}

message GoogleRequest {
      string token =1;
      int32 code = 2;
}

