// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: internal/domain/forgetpassword/forgetpassword.proto

package forgetpasswordproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForgetPassword_Forget_FullMethodName = "/forgetpasswordproto.ForgetPassword/Forget"
	ForgetPassword_Reset_FullMethodName  = "/forgetpasswordproto.ForgetPassword/Reset"
)

// ForgetPasswordClient is the client API for ForgetPassword service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForgetPasswordClient interface {
	Forget(ctx context.Context, in *ForgetRequest, opts ...grpc.CallOption) (*ForgetResponse, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
}

type forgetPasswordClient struct {
	cc grpc.ClientConnInterface
}

func NewForgetPasswordClient(cc grpc.ClientConnInterface) ForgetPasswordClient {
	return &forgetPasswordClient{cc}
}

func (c *forgetPasswordClient) Forget(ctx context.Context, in *ForgetRequest, opts ...grpc.CallOption) (*ForgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetResponse)
	err := c.cc.Invoke(ctx, ForgetPassword_Forget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgetPasswordClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, ForgetPassword_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForgetPasswordServer is the server API for ForgetPassword service.
// All implementations must embed UnimplementedForgetPasswordServer
// for forward compatibility.
type ForgetPasswordServer interface {
	Forget(context.Context, *ForgetRequest) (*ForgetResponse, error)
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	mustEmbedUnimplementedForgetPasswordServer()
}

// UnimplementedForgetPasswordServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForgetPasswordServer struct{}

func (UnimplementedForgetPasswordServer) Forget(context.Context, *ForgetRequest) (*ForgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forget not implemented")
}
func (UnimplementedForgetPasswordServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedForgetPasswordServer) mustEmbedUnimplementedForgetPasswordServer() {}
func (UnimplementedForgetPasswordServer) testEmbeddedByValue()                        {}

// UnsafeForgetPasswordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForgetPasswordServer will
// result in compilation errors.
type UnsafeForgetPasswordServer interface {
	mustEmbedUnimplementedForgetPasswordServer()
}

func RegisterForgetPasswordServer(s grpc.ServiceRegistrar, srv ForgetPasswordServer) {
	// If the following call pancis, it indicates UnimplementedForgetPasswordServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForgetPassword_ServiceDesc, srv)
}

func _ForgetPassword_Forget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgetPasswordServer).Forget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgetPassword_Forget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgetPasswordServer).Forget(ctx, req.(*ForgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgetPassword_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgetPasswordServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgetPassword_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgetPasswordServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForgetPassword_ServiceDesc is the grpc.ServiceDesc for ForgetPassword service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForgetPassword_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forgetpasswordproto.ForgetPassword",
	HandlerType: (*ForgetPasswordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forget",
			Handler:    _ForgetPassword_Forget_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _ForgetPassword_Reset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/domain/forgetpassword/forgetpassword.proto",
}
