// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/domain/forgetpassword/forgetpassword.proto

package forgetpasswordproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetResponse) Reset() {
	*x = ForgetResponse{}
	mi := &file_internal_domain_forgetpassword_forgetpassword_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetResponse) ProtoMessage() {}

func (x *ForgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_forgetpassword_forgetpassword_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetResponse.ProtoReflect.Descriptor instead.
func (*ForgetResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_forgetpassword_forgetpassword_proto_rawDescGZIP(), []int{0}
}

func (x *ForgetResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ForgetResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ForgetResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ForgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetRequest) Reset() {
	*x = ForgetRequest{}
	mi := &file_internal_domain_forgetpassword_forgetpassword_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetRequest) ProtoMessage() {}

func (x *ForgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_forgetpassword_forgetpassword_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetRequest.ProtoReflect.Descriptor instead.
func (*ForgetRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_forgetpassword_forgetpassword_proto_rawDescGZIP(), []int{1}
}

func (x *ForgetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_internal_domain_forgetpassword_forgetpassword_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_forgetpassword_forgetpassword_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_forgetpassword_forgetpassword_proto_rawDescGZIP(), []int{2}
}

func (x *ResetResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResetResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ResetRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Token                string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string                 `protobuf:"bytes,3,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_internal_domain_forgetpassword_forgetpassword_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_forgetpassword_forgetpassword_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_forgetpassword_forgetpassword_proto_rawDescGZIP(), []int{3}
}

func (x *ResetRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResetRequest) GetPasswordConfirmation() string {
	if x != nil {
		return x.PasswordConfirmation
	}
	return ""
}

var File_internal_domain_forgetpassword_forgetpassword_proto protoreflect.FileDescriptor

const file_internal_domain_forgetpassword_forgetpassword_proto_rawDesc = "" +
	"\n" +
	"3internal/domain/forgetpassword/forgetpassword.proto\x12\x13forgetpasswordproto\"L\n" +
	"\x0eForgetResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"%\n" +
	"\rForgetRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"5\n" +
	"\rResetResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"u\n" +
	"\fResetRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x123\n" +
	"\x15password_confirmation\x18\x03 \x01(\tR\x14passwordConfirmation2\xb7\x01\n" +
	"\x0eForgetPassword\x12Q\n" +
	"\x06Forget\x12\".forgetpasswordproto.ForgetRequest\x1a#.forgetpasswordproto.ForgetResponse\x12R\n" +
	"\tresetGRPC\x12!.forgetpasswordproto.ResetRequest\x1a\".forgetpasswordproto.ResetResponseB5Z3/internal/domain/forgetpassword/forgetpasswordprotob\x06proto3"

var (
	file_internal_domain_forgetpassword_forgetpassword_proto_rawDescOnce sync.Once
	file_internal_domain_forgetpassword_forgetpassword_proto_rawDescData []byte
)

func file_internal_domain_forgetpassword_forgetpassword_proto_rawDescGZIP() []byte {
	file_internal_domain_forgetpassword_forgetpassword_proto_rawDescOnce.Do(func() {
		file_internal_domain_forgetpassword_forgetpassword_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_domain_forgetpassword_forgetpassword_proto_rawDesc), len(file_internal_domain_forgetpassword_forgetpassword_proto_rawDesc)))
	})
	return file_internal_domain_forgetpassword_forgetpassword_proto_rawDescData
}

var file_internal_domain_forgetpassword_forgetpassword_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_domain_forgetpassword_forgetpassword_proto_goTypes = []any{
	(*ForgetResponse)(nil), // 0: forgetpasswordproto.ForgetResponse
	(*ForgetRequest)(nil),  // 1: forgetpasswordproto.ForgetRequest
	(*ResetResponse)(nil),  // 2: forgetpasswordproto.ResetResponse
	(*ResetRequest)(nil),   // 3: forgetpasswordproto.ResetRequest
}
var file_internal_domain_forgetpassword_forgetpassword_proto_depIdxs = []int32{
	1, // 0: forgetpasswordproto.ForgetPassword.Forget:input_type -> forgetpasswordproto.ForgetRequest
	3, // 1: forgetpasswordproto.ForgetPassword.resetGRPC:input_type -> forgetpasswordproto.ResetRequest
	0, // 2: forgetpasswordproto.ForgetPassword.Forget:output_type -> forgetpasswordproto.ForgetResponse
	2, // 3: forgetpasswordproto.ForgetPassword.resetGRPC:output_type -> forgetpasswordproto.ResetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_domain_forgetpassword_forgetpassword_proto_init() }
func file_internal_domain_forgetpassword_forgetpassword_proto_init() {
	if File_internal_domain_forgetpassword_forgetpassword_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_domain_forgetpassword_forgetpassword_proto_rawDesc), len(file_internal_domain_forgetpassword_forgetpassword_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_domain_forgetpassword_forgetpassword_proto_goTypes,
		DependencyIndexes: file_internal_domain_forgetpassword_forgetpassword_proto_depIdxs,
		MessageInfos:      file_internal_domain_forgetpassword_forgetpassword_proto_msgTypes,
	}.Build()
	File_internal_domain_forgetpassword_forgetpassword_proto = out.File
	file_internal_domain_forgetpassword_forgetpassword_proto_goTypes = nil
	file_internal_domain_forgetpassword_forgetpassword_proto_depIdxs = nil
}
