// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	twofactornotifierproto "github.com/sajad-dev/authservice/authentication/internal/domain/twofactornotifier/twofactornotifierproto"
	mock "github.com/stretchr/testify/mock"
)

// TwofactorNotifierServer is an autogenerated mock type for the TwofactorNotifierServer type
type TwofactorNotifierServer struct {
	mock.Mock
}

// NotifierEmail provides a mock function with given fields: _a0, _a1
func (_m *TwofactorNotifierServer) NotifierEmail(_a0 context.Context, _a1 *twofactornotifierproto.NotifierEmailRequest) (*twofactornotifierproto.TwoFactorNotifierResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for NotifierEmail")
	}

	var r0 *twofactornotifierproto.TwoFactorNotifierResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *twofactornotifierproto.NotifierEmailRequest) (*twofactornotifierproto.TwoFactorNotifierResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *twofactornotifierproto.NotifierEmailRequest) *twofactornotifierproto.TwoFactorNotifierResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twofactornotifierproto.TwoFactorNotifierResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *twofactornotifierproto.NotifierEmailRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedTwofactorNotifierServer provides a mock function with no fields
func (_m *TwofactorNotifierServer) mustEmbedUnimplementedTwofactorNotifierServer() {
	_m.Called()
}

// NewTwofactorNotifierServer creates a new instance of TwofactorNotifierServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTwofactorNotifierServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TwofactorNotifierServer {
	mock := &TwofactorNotifierServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
