// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	twofactornotifierproto "github.com/sajad-dev/authservice/authentication/internal/domain/twofactornotifier/twofactornotifierproto"
)

// TwofactorNotifierClient is an autogenerated mock type for the TwofactorNotifierClient type
type TwofactorNotifierClient struct {
	mock.Mock
}

// NotifierEmail provides a mock function with given fields: ctx, in, opts
func (_m *TwofactorNotifierClient) NotifierEmail(ctx context.Context, in *twofactornotifierproto.NotifierEmailRequest, opts ...grpc.CallOption) (*twofactornotifierproto.TwoFactorNotifierResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for NotifierEmail")
	}

	var r0 *twofactornotifierproto.TwoFactorNotifierResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *twofactornotifierproto.NotifierEmailRequest, ...grpc.CallOption) (*twofactornotifierproto.TwoFactorNotifierResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *twofactornotifierproto.NotifierEmailRequest, ...grpc.CallOption) *twofactornotifierproto.TwoFactorNotifierResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twofactornotifierproto.TwoFactorNotifierResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *twofactornotifierproto.NotifierEmailRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTwofactorNotifierClient creates a new instance of TwofactorNotifierClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTwofactorNotifierClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TwofactorNotifierClient {
	mock := &TwofactorNotifierClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
