// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	request "github.com/sajad-dev/authservice/authentication/internal/domain/twofactornotifier/dto/gen/request"
	response "github.com/sajad-dev/authservice/authentication/internal/domain/twofactornotifier/dto/gen/response"
	mock "github.com/stretchr/testify/mock"
)

// TwoFactorNotifierService is an autogenerated mock type for the TwoFactorNotifierService type
type TwoFactorNotifierService struct {
	mock.Mock
}

// NotifierEmail provides a mock function with given fields: req
func (_m *TwoFactorNotifierService) NotifierEmail(req request.NotifierEmailRequest) (response.TwoFactorNotifierResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for NotifierEmail")
	}

	var r0 response.TwoFactorNotifierResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.NotifierEmailRequest) (response.TwoFactorNotifierResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.NotifierEmailRequest) response.TwoFactorNotifierResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.TwoFactorNotifierResponse)
	}

	if rf, ok := ret.Get(1).(func(request.NotifierEmailRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTwoFactorNotifierService creates a new instance of TwoFactorNotifierService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTwoFactorNotifierService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TwoFactorNotifierService {
	mock := &TwoFactorNotifierService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
