// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	twofactornotifierproto "github.com/sajad-dev/authservice/authentication/internal/domain/twofactornotifier/twofactornotifierproto"
)

// TwoFactorNotifierHandler is an autogenerated mock type for the TwoFactorNotifierHandler type
type TwoFactorNotifierHandler struct {
	mock.Mock
}

// NotifierEmail provides a mock function with given fields: req
func (_m *TwoFactorNotifierHandler) NotifierEmail(req *twofactornotifierproto.NotifierEmailRequest) (*twofactornotifierproto.TwoFactorNotifierResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for NotifierEmail")
	}

	var r0 *twofactornotifierproto.TwoFactorNotifierResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*twofactornotifierproto.NotifierEmailRequest) (*twofactornotifierproto.TwoFactorNotifierResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*twofactornotifierproto.NotifierEmailRequest) *twofactornotifierproto.TwoFactorNotifierResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twofactornotifierproto.TwoFactorNotifierResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*twofactornotifierproto.NotifierEmailRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTwoFactorNotifierHandler creates a new instance of TwoFactorNotifierHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTwoFactorNotifierHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TwoFactorNotifierHandler {
	mock := &TwoFactorNotifierHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
