// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/sajad-dev/authservice/authentication/internal/shared/models"
	mock "github.com/stretchr/testify/mock"
)

// TwoFactorNotifierRepository is an autogenerated mock type for the TwoFactorNotifierRepository type
type TwoFactorNotifierRepository struct {
	mock.Mock
}

// CreateCode provides a mock function with given fields: row
func (_m *TwoFactorNotifierRepository) CreateCode(row *models.TwoFactorCode) error {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for CreateCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.TwoFactorCode) error); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *TwoFactorNotifierRepository) FindById(id int) (*models.Accounts, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *models.Accounts
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Accounts, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Accounts); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Accounts)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveExpierd provides a mock function with given fields: id
func (_m *TwoFactorNotifierRepository) RemoveExpierd(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveExpierd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTwoFactorNotifierRepository creates a new instance of TwoFactorNotifierRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTwoFactorNotifierRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TwoFactorNotifierRepository {
	mock := &TwoFactorNotifierRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
