syntax = "proto3";

package groupproto;

import "google/api/annotations.proto";

option go_package = "/internal/domain/group/groupproto";

service Group {
  rpc Create (CreateRequest) returns (Response) {
    option (google.api.http) = {
      post: "/group"
      body: "*"
    };
  }

  rpc Delete (DeleteRequest) returns (Response) {
    option (google.api.http) = {
      delete: "/group/{id}"
    };
  }

  rpc GetAll (GetAllRequest) returns (GetAllResponse) {
    option (google.api.http) = {
      get: "/group"
    };
  }
}


message Response {
  int32 code = 1;
  string msg = 2;
}
message PolicyList {
    repeated string policy = 1;
}
message GetAllResponse {
  int32 code = 1;
  string msg = 2;
  repeated PolicyList data = 3 ;
}

message CreateRequest {

