// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SqlDBGlobal is an autogenerated mock type for the SqlDBGlobal type
type SqlDBGlobal struct {
	mock.Mock
}

// Exists provides a mock function with given fields: tablename, fieldname, value
func (_m *SqlDBGlobal) Exists(tablename string, fieldname string, value string) bool {
	ret := _m.Called(tablename, fieldname, value)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(tablename, fieldname, value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewSqlDBGlobal creates a new instance of SqlDBGlobal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSqlDBGlobal(t interface {
	mock.TestingT
	Cleanup(func())
}) *SqlDBGlobal {
	mock := &SqlDBGlobal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
