// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// SqlDB is an autogenerated mock type for the SqlDB type
type SqlDB[M interface{}] struct {
	mock.Mock
}

// Create provides a mock function with given fields: params
func (_m *SqlDB[M]) Create(params M) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(M) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *SqlDB[M]) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *SqlDB[M]) GetByID(id int) (M, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 M
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (M, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) M); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(M)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveExpierd provides a mock function with given fields: column, id
func (_m *SqlDB[M]) RemoveExpierd(column string, id int) error {
	ret := _m.Called(column, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveExpierd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(column, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: params
func (_m *SqlDB[M]) Save(params M) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(M) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Table provides a mock function with given fields: _a0
func (_m *SqlDB[M]) Table(_a0 string) *gorm.DB {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Table")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(string) *gorm.DB); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Where provides a mock function with given fields: params
func (_m *SqlDB[M]) Where(params M) ([]M, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Where")
	}

	var r0 []M
	var r1 error
	if rf, ok := ret.Get(0).(func(M) ([]M, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(M) []M); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]M)
		}
	}

	if rf, ok := ret.Get(1).(func(M) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WhereField provides a mock function with given fields: column, value
func (_m *SqlDB[M]) WhereField(column string, value string) (M, error) {
	ret := _m.Called(column, value)

	if len(ret) == 0 {
		panic("no return value specified for WhereField")
	}

	var r0 M
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (M, error)); ok {
		return rf(column, value)
	}
	if rf, ok := ret.Get(0).(func(string, string) M); ok {
		r0 = rf(column, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(M)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(column, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSqlDB creates a new instance of SqlDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSqlDB[M interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *SqlDB[M] {
	mock := &SqlDB[M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
