// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/domain/twofactornotifier/twofactornotifier.proto

package twofactornotifierproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TwoFactorNotifierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoFactorNotifierResponse) Reset() {
	*x = TwoFactorNotifierResponse{}
	mi := &file_internal_domain_twofactornotifier_twofactornotifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoFactorNotifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoFactorNotifierResponse) ProtoMessage() {}

func (x *TwoFactorNotifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_twofactornotifier_twofactornotifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoFactorNotifierResponse.ProtoReflect.Descriptor instead.
func (*TwoFactorNotifierResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDescGZIP(), []int{0}
}

func (x *TwoFactorNotifierResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TwoFactorNotifierResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type NotifierEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifierEmailRequest) Reset() {
	*x = NotifierEmailRequest{}
	mi := &file_internal_domain_twofactornotifier_twofactornotifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifierEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifierEmailRequest) ProtoMessage() {}

func (x *NotifierEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_twofactornotifier_twofactornotifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifierEmailRequest.ProtoReflect.Descriptor instead.
func (*NotifierEmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDescGZIP(), []int{1}
}

func (x *NotifierEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_internal_domain_twofactornotifier_twofactornotifier_proto protoreflect.FileDescriptor

const file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDesc = "" +
	"\n" +
	"9internal/domain/twofactornotifier/twofactornotifier.proto\x12\x16twofactornotifierproto\"A\n" +
	"\x19TwoFactorNotifierResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\",\n" +
	"\x14NotifierEmailRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\x85\x01\n" +
	"\x11TwofactorNotifier\x12p\n" +
	"\rNotifierEmail\x12,.twofactornotifierproto.NotifierEmailRequest\x1a1.twofactornotifierproto.TwoFactorNotifierResponseB;Z9/internal/domain/twofactornotifier/twofactornotifierprotob\x06proto3"

var (
	file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDescOnce sync.Once
	file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDescData []byte
)

func file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDescGZIP() []byte {
	file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDescOnce.Do(func() {
		file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDesc), len(file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDesc)))
	})
	return file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDescData
}

var file_internal_domain_twofactornotifier_twofactornotifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_domain_twofactornotifier_twofactornotifier_proto_goTypes = []any{
	(*TwoFactorNotifierResponse)(nil), // 0: twofactornotifierproto.TwoFactorNotifierResponse
	(*NotifierEmailRequest)(nil),      // 1: twofactornotifierproto.NotifierEmailRequest
}
var file_internal_domain_twofactornotifier_twofactornotifier_proto_depIdxs = []int32{
	1, // 0: twofactornotifierproto.TwofactorNotifier.NotifierEmail:input_type -> twofactornotifierproto.NotifierEmailRequest
	0, // 1: twofactornotifierproto.TwofactorNotifier.NotifierEmail:output_type -> twofactornotifierproto.TwoFactorNotifierResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_domain_twofactornotifier_twofactornotifier_proto_init() }
func file_internal_domain_twofactornotifier_twofactornotifier_proto_init() {
	if File_internal_domain_twofactornotifier_twofactornotifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDesc), len(file_internal_domain_twofactornotifier_twofactornotifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_domain_twofactornotifier_twofactornotifier_proto_goTypes,
		DependencyIndexes: file_internal_domain_twofactornotifier_twofactornotifier_proto_depIdxs,
		MessageInfos:      file_internal_domain_twofactornotifier_twofactornotifier_proto_msgTypes,
	}.Build()
	File_internal_domain_twofactornotifier_twofactornotifier_proto = out.File
	file_internal_domain_twofactornotifier_twofactornotifier_proto_goTypes = nil
	file_internal_domain_twofactornotifier_twofactornotifier_proto_depIdxs = nil
}
