// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/domain/twofactor/twofactor.proto

package twofactorproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	TwoFactor     []string               `protobuf:"bytes,6,rep,name=two_factor,json=twoFactor,proto3" json:"two_factor,omitempty"`
	Id            int32                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_domain_twofactor_twofactor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_twofactor_twofactor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_domain_twofactor_twofactor_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetTwoFactor() []string {
	if x != nil {
		return x.TwoFactor
	}
	return nil
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TwoFactorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *User                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoFactorResponse) Reset() {
	*x = TwoFactorResponse{}
	mi := &file_internal_domain_twofactor_twofactor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoFactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoFactorResponse) ProtoMessage() {}

func (x *TwoFactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_twofactor_twofactor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoFactorResponse.ProtoReflect.Descriptor instead.
func (*TwoFactorResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_twofactor_twofactor_proto_rawDescGZIP(), []int{1}
}

func (x *TwoFactorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TwoFactorResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TwoFactorResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TwoFactorResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_internal_domain_twofactor_twofactor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_twofactor_twofactor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_twofactor_twofactor_proto_rawDescGZIP(), []int{2}
}

func (x *EmailRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GoogleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleRequest) Reset() {
	*x = GoogleRequest{}
	mi := &file_internal_domain_twofactor_twofactor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleRequest) ProtoMessage() {}

func (x *GoogleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_twofactor_twofactor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleRequest.ProtoReflect.Descriptor instead.
func (*GoogleRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_twofactor_twofactor_proto_rawDescGZIP(), []int{3}
}

func (x *GoogleRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GoogleRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_internal_domain_twofactor_twofactor_proto protoreflect.FileDescriptor

const file_internal_domain_twofactor_twofactor_proto_rawDesc = "" +
	"\n" +
	")internal/domain/twofactor/twofactor.proto\x12\x0etwofactorproto\"\xa3\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"two_factor\x18\x06 \x03(\tR\ttwoFactor\x12\x0e\n" +
	"\x02id\x18\a \x01(\x05R\x02id\"y\n" +
	"\x11TwoFactorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.twofactorproto.UserR\x04data\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\"\n" +
	"\fEmailRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"9\n" +
	"\rGoogleRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\xa2\x01\n" +
	"\n" +
	"Twofactory\x12H\n" +
	"\x05Email\x12\x1c.twofactorproto.EmailRequest\x1a!.twofactorproto.TwoFactorResponse\x12J\n" +
	"\x06Google\x12\x1d.twofactorproto.GoogleRequest\x1a!.twofactorproto.TwoFactorResponseB+Z)/internal/domain/twofactor/twofactorprotob\x06proto3"

var (
	file_internal_domain_twofactor_twofactor_proto_rawDescOnce sync.Once
	file_internal_domain_twofactor_twofactor_proto_rawDescData []byte
)

func file_internal_domain_twofactor_twofactor_proto_rawDescGZIP() []byte {
	file_internal_domain_twofactor_twofactor_proto_rawDescOnce.Do(func() {
		file_internal_domain_twofactor_twofactor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_domain_twofactor_twofactor_proto_rawDesc), len(file_internal_domain_twofactor_twofactor_proto_rawDesc)))
	})
	return file_internal_domain_twofactor_twofactor_proto_rawDescData
}

var file_internal_domain_twofactor_twofactor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_domain_twofactor_twofactor_proto_goTypes = []any{
	(*User)(nil),              // 0: twofactorproto.User
	(*TwoFactorResponse)(nil), // 1: twofactorproto.TwoFactorResponse
	(*EmailRequest)(nil),      // 2: twofactorproto.EmailRequest
	(*GoogleRequest)(nil),     // 3: twofactorproto.GoogleRequest
}
var file_internal_domain_twofactor_twofactor_proto_depIdxs = []int32{
	0, // 0: twofactorproto.TwoFactorResponse.data:type_name -> twofactorproto.User
	2, // 1: twofactorproto.Twofactory.Email:input_type -> twofactorproto.EmailRequest
	3, // 2: twofactorproto.Twofactory.Google:input_type -> twofactorproto.GoogleRequest
	1, // 3: twofactorproto.Twofactory.Email:output_type -> twofactorproto.TwoFactorResponse
	1, // 4: twofactorproto.Twofactory.Google:output_type -> twofactorproto.TwoFactorResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_domain_twofactor_twofactor_proto_init() }
func file_internal_domain_twofactor_twofactor_proto_init() {
	if File_internal_domain_twofactor_twofactor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_domain_twofactor_twofactor_proto_rawDesc), len(file_internal_domain_twofactor_twofactor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_domain_twofactor_twofactor_proto_goTypes,
		DependencyIndexes: file_internal_domain_twofactor_twofactor_proto_depIdxs,
		MessageInfos:      file_internal_domain_twofactor_twofactor_proto_msgTypes,
	}.Build()
	File_internal_domain_twofactor_twofactor_proto = out.File
	file_internal_domain_twofactor_twofactor_proto_goTypes = nil
	file_internal_domain_twofactor_twofactor_proto_depIdxs = nil
}
