// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: internal/domain/twofactor/twofactor.proto

package twofactorproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Twofactor_Email_FullMethodName  = "/twofactorproto.Twofactor/Email"
	Twofactor_Google_FullMethodName = "/twofactorproto.Twofactor/Google"
)

// TwofactorClient is the client API for Twofactor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TwofactorClient interface {
	Email(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*TwoFactorResponse, error)
	Google(ctx context.Context, in *GoogleRequest, opts ...grpc.CallOption) (*TwoFactorResponse, error)
}

type twofactorClient struct {
	cc grpc.ClientConnInterface
}

func NewTwofactorClient(cc grpc.ClientConnInterface) TwofactorClient {
	return &twofactorClient{cc}
}

func (c *twofactorClient) Email(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*TwoFactorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwoFactorResponse)
	err := c.cc.Invoke(ctx, Twofactor_Email_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twofactorClient) Google(ctx context.Context, in *GoogleRequest, opts ...grpc.CallOption) (*TwoFactorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwoFactorResponse)
	err := c.cc.Invoke(ctx, Twofactor_Google_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwofactorServer is the server API for Twofactor service.
// All implementations must embed UnimplementedTwofactorServer
// for forward compatibility.
type TwofactorServer interface {
	Email(context.Context, *EmailRequest) (*TwoFactorResponse, error)
	Google(context.Context, *GoogleRequest) (*TwoFactorResponse, error)
	mustEmbedUnimplementedTwofactorServer()
}

// UnimplementedTwofactorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTwofactorServer struct{}

func (UnimplementedTwofactorServer) Email(context.Context, *EmailRequest) (*TwoFactorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Email not implemented")
}
func (UnimplementedTwofactorServer) Google(context.Context, *GoogleRequest) (*TwoFactorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Google not implemented")
}
func (UnimplementedTwofactorServer) mustEmbedUnimplementedTwofactorServer() {}
func (UnimplementedTwofactorServer) testEmbeddedByValue()                   {}

// UnsafeTwofactorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwofactorServer will
// result in compilation errors.
type UnsafeTwofactorServer interface {
	mustEmbedUnimplementedTwofactorServer()
}

func RegisterTwofactorServer(s grpc.ServiceRegistrar, srv TwofactorServer) {
	// If the following call pancis, it indicates UnimplementedTwofactorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Twofactor_ServiceDesc, srv)
}

func _Twofactor_Email_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwofactorServer).Email(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twofactor_Email_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwofactorServer).Email(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twofactor_Google_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwofactorServer).Google(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twofactor_Google_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwofactorServer).Google(ctx, req.(*GoogleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Twofactor_ServiceDesc is the grpc.ServiceDesc for Twofactor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Twofactor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "twofactorproto.Twofactor",
	HandlerType: (*TwofactorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Email",
			Handler:    _Twofactor_Email_Handler,
		},
		{
			MethodName: "Google",
			Handler:    _Twofactor_Google_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/domain/twofactor/twofactor.proto",
}
