// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	request "github.com/sajad-dev/authservice/internal/domain/account/dto/gen/request"
	response "github.com/sajad-dev/authservice/internal/domain/account/dto/gen/response"
	mock "github.com/stretchr/testify/mock"
)

// AccountCURDService is an autogenerated mock type for the AccountCURDService type
type AccountCURDService struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *AccountCURDService) Create(req request.CreateRequest) (response.CreateResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 response.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CreateRequest) (response.CreateResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.CreateRequest) response.CreateResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.CreateResponse)
	}

	if rf, ok := ret.Get(1).(func(request.CreateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: req
func (_m *AccountCURDService) Delete(req request.DeleteRequest) (response.DeleteResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 response.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.DeleteRequest) (response.DeleteResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.DeleteRequest) response.DeleteResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.DeleteResponse)
	}

	if rf, ok := ret.Get(1).(func(request.DeleteRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: req
func (_m *AccountCURDService) Read(req request.ReadRequest) (response.ReadResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 response.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.ReadRequest) (response.ReadResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.ReadRequest) response.ReadResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.ReadResponse)
	}

	if rf, ok := ret.Get(1).(func(request.ReadRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: req
func (_m *AccountCURDService) Update(req request.UpdateRequest) (response.UpdateResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 response.UpdateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.UpdateRequest) (response.UpdateResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.UpdateRequest) response.UpdateResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.UpdateResponse)
	}

	if rf, ok := ret.Get(1).(func(request.UpdateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountCURDService creates a new instance of AccountCURDService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountCURDService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountCURDService {
	mock := &AccountCURDService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
