// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	accountproto "github.com/sajad-dev/authservice/internal/domain/account/accountproto"

	mock "github.com/stretchr/testify/mock"
)

// AccountServer is an autogenerated mock type for the AccountServer type
type AccountServer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *AccountServer) Create(_a0 context.Context, _a1 *accountproto.CreateRequest) (*accountproto.CreateResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *accountproto.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.CreateRequest) (*accountproto.CreateResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.CreateRequest) *accountproto.CreateResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *accountproto.CreateRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *AccountServer) Delete(_a0 context.Context, _a1 *accountproto.DeleteRequest) (*accountproto.DeleteResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *accountproto.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.DeleteRequest) (*accountproto.DeleteResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.DeleteRequest) *accountproto.DeleteResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *accountproto.DeleteRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: _a0, _a1
func (_m *AccountServer) Read(_a0 context.Context, _a1 *accountproto.ReadRequest) (*accountproto.ReadResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *accountproto.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.ReadRequest) (*accountproto.ReadResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.ReadRequest) *accountproto.ReadResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.ReadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *accountproto.ReadRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *AccountServer) Update(_a0 context.Context, _a1 *accountproto.UpdateRequest) (*accountproto.UpdateResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *accountproto.UpdateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.UpdateRequest) (*accountproto.UpdateResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *accountproto.UpdateRequest) *accountproto.UpdateResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.UpdateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *accountproto.UpdateRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedAccountServer provides a mock function with no fields
func (_m *AccountServer) mustEmbedUnimplementedAccountServer() {
	_m.Called()
}

// NewAccountServer creates a new instance of AccountServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountServer {
	mock := &AccountServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
