// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	accountproto "github.com/sajad-dev/authservice/internal/domain/account/accountproto"
	mock "github.com/stretchr/testify/mock"
)

// AccountCURDHandler is an autogenerated mock type for the AccountCURDHandler type
type AccountCURDHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *AccountCURDHandler) Create(req *accountproto.CreateRequest) (*accountproto.CreateResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *accountproto.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*accountproto.CreateRequest) (*accountproto.CreateResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*accountproto.CreateRequest) *accountproto.CreateResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*accountproto.CreateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: req
func (_m *AccountCURDHandler) Delete(req *accountproto.DeleteRequest) (*accountproto.DeleteResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *accountproto.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*accountproto.DeleteRequest) (*accountproto.DeleteResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*accountproto.DeleteRequest) *accountproto.DeleteResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*accountproto.DeleteRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: req
func (_m *AccountCURDHandler) Read(req *accountproto.ReadRequest) (*accountproto.ReadResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *accountproto.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*accountproto.ReadRequest) (*accountproto.ReadResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*accountproto.ReadRequest) *accountproto.ReadResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.ReadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*accountproto.ReadRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: req
func (_m *AccountCURDHandler) Update(req *accountproto.UpdateRequest) (*accountproto.UpdateResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *accountproto.UpdateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*accountproto.UpdateRequest) (*accountproto.UpdateResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*accountproto.UpdateRequest) *accountproto.UpdateResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountproto.UpdateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*accountproto.UpdateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountCURDHandler creates a new instance of AccountCURDHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountCURDHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountCURDHandler {
	mock := &AccountCURDHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
