// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	request "github.com/sajad-dev/authservice/authentication/internal/domain/authentication/dto/gen/request"
	response "github.com/sajad-dev/authservice/authentication/internal/domain/authentication/dto/gen/response"
	mock "github.com/stretchr/testify/mock"
)

// AuthenticatorService is an autogenerated mock type for the AuthenticatorService type
type AuthenticatorService struct {
	mock.Mock
}

// Login provides a mock function with given fields: req
func (_m *AuthenticatorService) Login(req request.LoginRequest) (response.LoginResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 response.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.LoginRequest) (response.LoginResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.LoginRequest) response.LoginResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(request.LoginRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: req
func (_m *AuthenticatorService) Register(req request.RegisterRequest) (response.RegisterResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 response.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.RegisterRequest) (response.RegisterResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.RegisterRequest) response.RegisterResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.RegisterResponse)
	}

	if rf, ok := ret.Get(1).(func(request.RegisterRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthenticatorService creates a new instance of AuthenticatorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticatorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticatorService {
	mock := &AuthenticatorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
