// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	authenticationproto "github.com/sajad-dev/authservice/authentication/internal/domain/authentication/authenticationproto"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// AuthenticationClient is an autogenerated mock type for the AuthenticationClient type
type AuthenticationClient struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *AuthenticationClient) Login(ctx context.Context, in *authenticationproto.LoginRequest, opts ...grpc.CallOption) (*authenticationproto.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *authenticationproto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authenticationproto.LoginRequest, ...grpc.CallOption) (*authenticationproto.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authenticationproto.LoginRequest, ...grpc.CallOption) *authenticationproto.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authenticationproto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authenticationproto.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *AuthenticationClient) Register(ctx context.Context, in *authenticationproto.RegisterRequest, opts ...grpc.CallOption) (*authenticationproto.RegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *authenticationproto.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authenticationproto.RegisterRequest, ...grpc.CallOption) (*authenticationproto.RegisterResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authenticationproto.RegisterRequest, ...grpc.CallOption) *authenticationproto.RegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authenticationproto.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authenticationproto.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthenticationClient creates a new instance of AuthenticationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationClient {
	mock := &AuthenticationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
