// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	authenticationproto "github.com/sajad-dev/authservice/authentication/internal/domain/authentication/authenticationproto"

	mock "github.com/stretchr/testify/mock"
)

// AuthenticationServer is an autogenerated mock type for the AuthenticationServer type
type AuthenticationServer struct {
	mock.Mock
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *AuthenticationServer) Login(_a0 context.Context, _a1 *authenticationproto.LoginRequest) (*authenticationproto.LoginResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *authenticationproto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authenticationproto.LoginRequest) (*authenticationproto.LoginResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authenticationproto.LoginRequest) *authenticationproto.LoginResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authenticationproto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authenticationproto.LoginRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *AuthenticationServer) Register(_a0 context.Context, _a1 *authenticationproto.RegisterRequest) (*authenticationproto.RegisterResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *authenticationproto.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authenticationproto.RegisterRequest) (*authenticationproto.RegisterResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authenticationproto.RegisterRequest) *authenticationproto.RegisterResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authenticationproto.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authenticationproto.RegisterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedAuthenticationServer provides a mock function with no fields
func (_m *AuthenticationServer) mustEmbedUnimplementedAuthenticationServer() {
	_m.Called()
}

// NewAuthenticationServer creates a new instance of AuthenticationServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationServer {
	mock := &AuthenticationServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
