syntax = "proto3";

package accountproto;

import "google/api/annotations.proto";

option go_package = "/internal/domain/account/accountproto";

service Account {
  rpc Create (CreateRequest) returns (CreateResponse) {
    option (google.api.http) = {
      post: "/account"
      body: "*"
    };
  }

  rpc Update (UpdateRequest) returns (UpdateResponse) {
    option (google.api.http) = {
      put: "/account/{id}"
      body: "*"
    };
  }

  rpc Delete (DeleteRequest) returns (DeleteResponse) {
    option (google.api.http) = {
      delete: "/account/{id}"
    };
  }

  rpc Read (ReadRequest) returns (ReadResponse) {
    option (google.api.http) = {
      get: "/account/{id}"
    };
  }
}


message CreateResponse {
  int32 code = 1;
  string msg = 2;
}
message CreateRequest {
  string username = 1;
  string email = 2;
  string first_name = 4;
  string last_name =5;
  repeated string two_factor = 6;
  string password = 7;
  string password_confirmation = 8;

}


message UpdateResponse {
  int32 code = 1;
  string msg = 2;
}
message UpdateRequest {
  string username = 1;
  string email = 2;
  string first_name = 4;
  string last_name =5;
  repeated string two_factor = 6;
  int32 id =7;
  string password = 8;
  string password_confirmation = 9;
}

message DeleteResponse {
  int32 code = 1;
  string msg = 2;
}
message DeleteRequest {
  int32 id =8;
}

message User {
    string username = 1;
    string email = 2;
    string first_name = 4;
    string last_name =5;
    repeated string two_factor = 6;
    int32 id =7;
}

message ReadResponse {
  int32 code = 1;
  string msg = 2;
  User Data = 3;
}

message ReadRequest {
    int32 id =8;
}



