syntax = "proto3";

package forgetpasswordproto;

option go_package = "/internal/domain/forgetpassword/forgetpasswordproto";

service ForgetPassword {
  rpc Forget (ForgetRequest) returns (ForgetResponse);
  rpc resetGRPC (ResetRequest) returns (ResetResponse);
}

message ForgetResponse {
  int32 code = 1;
  string msg = 2;
  string token = 3;
}

message ForgetRequest {
      string email = 1;
}

message ResetResponse {
    int32 code = 1;
    string msg = 2;
}

message ResetRequest {
  string token =1 ;
  string password =2 ;
  string password_confirmation = 3;
}
