// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/domain/group/group.proto

package groupproto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_domain_group_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_group_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_domain_group_group_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GroupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         []string               `protobuf:"bytes,1,rep,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupList) Reset() {
	*x = GroupList{}
	mi := &file_internal_domain_group_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupList) ProtoMessage() {}

func (x *GroupList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_group_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupList.ProtoReflect.Descriptor instead.
func (*GroupList) Descriptor() ([]byte, []int) {
	return file_internal_domain_group_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupList) GetGroup() []string {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*GroupList           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_internal_domain_group_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_group_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_group_group_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAllResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetAllResponse) GetData() []*GroupList {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=Group,proto3" json:"Group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_internal_domain_group_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_group_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_group_group_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=Group,proto3" json:"Group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_domain_group_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_group_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_group_group_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *DeleteRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_internal_domain_group_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_group_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_group_group_proto_rawDescGZIP(), []int{5}
}

var File_internal_domain_group_group_proto protoreflect.FileDescriptor

const file_internal_domain_group_group_proto_rawDesc = "" +
	"\n" +
	"!internal/domain/group/group.proto\x12\n" +
	"groupproto\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"!\n" +
	"\tGroupList\x12\x14\n" +
	"\x05group\x18\x01 \x03(\tR\x05group\"a\n" +
	"\x0eGetAllResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.groupproto.GroupListR\x04data\"?\n" +
	"\rCreateRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05Group\x18\x02 \x01(\tR\x05Group\"?\n" +
	"\rDeleteRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05Group\x18\x02 \x01(\tR\x05Group\"\x0f\n" +
	"\rGetAllRequest2\xf6\x01\n" +
	"\x05Group\x12L\n" +
	"\x06Create\x12\x19.groupproto.CreateRequest\x1a\x14.groupproto.Response\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/group\x12N\n" +
	"\x06Delete\x12\x19.groupproto.DeleteRequest\x1a\x14.groupproto.Response\"\x13\x82\xd3\xe4\x93\x02\r*\v/group/{id}\x12O\n" +
	"\x06GetAll\x12\x19.groupproto.GetAllRequest\x1a\x1a.groupproto.GetAllResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/groupB#Z!/internal/domain/group/groupprotob\x06proto3"

var (
	file_internal_domain_group_group_proto_rawDescOnce sync.Once
	file_internal_domain_group_group_proto_rawDescData []byte
)

func file_internal_domain_group_group_proto_rawDescGZIP() []byte {
	file_internal_domain_group_group_proto_rawDescOnce.Do(func() {
		file_internal_domain_group_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_domain_group_group_proto_rawDesc), len(file_internal_domain_group_group_proto_rawDesc)))
	})
	return file_internal_domain_group_group_proto_rawDescData
}

var file_internal_domain_group_group_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_domain_group_group_proto_goTypes = []any{
	(*Response)(nil),       // 0: groupproto.Response
	(*GroupList)(nil),      // 1: groupproto.GroupList
	(*GetAllResponse)(nil), // 2: groupproto.GetAllResponse
	(*CreateRequest)(nil),  // 3: groupproto.CreateRequest
	(*DeleteRequest)(nil),  // 4: groupproto.DeleteRequest
	(*GetAllRequest)(nil),  // 5: groupproto.GetAllRequest
}
var file_internal_domain_group_group_proto_depIdxs = []int32{
	1, // 0: groupproto.GetAllResponse.data:type_name -> groupproto.GroupList
	3, // 1: groupproto.Group.Create:input_type -> groupproto.CreateRequest
	4, // 2: groupproto.Group.Delete:input_type -> groupproto.DeleteRequest
	5, // 3: groupproto.Group.GetAll:input_type -> groupproto.GetAllRequest
	0, // 4: groupproto.Group.Create:output_type -> groupproto.Response
	0, // 5: groupproto.Group.Delete:output_type -> groupproto.Response
	2, // 6: groupproto.Group.GetAll:output_type -> groupproto.GetAllResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_domain_group_group_proto_init() }
func file_internal_domain_group_group_proto_init() {
	if File_internal_domain_group_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_domain_group_group_proto_rawDesc), len(file_internal_domain_group_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_domain_group_group_proto_goTypes,
		DependencyIndexes: file_internal_domain_group_group_proto_depIdxs,
		MessageInfos:      file_internal_domain_group_group_proto_msgTypes,
	}.Build()
	File_internal_domain_group_group_proto = out.File
	file_internal_domain_group_group_proto_goTypes = nil
	file_internal_domain_group_group_proto_depIdxs = nil
}
