syntax = "proto3";

package policyproto;

option go_package = "/internal/domain/policy/policyproto";

service Policy {
  rpc Create (CreateRequest) returns (Response);
  rpc Delete (DeleteRequest) returns (Response);
  rpc GetAll (GetAllRequest) returns (GetAllResponse);
}

message Response {
  int32 code = 1;
  string msg = 2;
}
message PolicyList {
    repeated string policy = 1;
}
message GetAllResponse {
  int32 code = 1;
  string msg = 2;
  repeated PolicyList data = 3 ;
}

message CreateRequest {
      string subject = 1;
      string object = 2;
      string action = 3;
}

message DeleteRequest {
      string subject = 1;
      string object = 2;
      string action = 3;
}

message GetAllRequest {
}
