// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	authenticationproto "github.com/sajad-dev/authservice/internal/domain/authentication/authenticationproto"
	mock "github.com/stretchr/testify/mock"
)

// AuthenticatorHandler is an autogenerated mock type for the AuthenticatorHandler type
type AuthenticatorHandler struct {
	mock.Mock
}

// Login provides a mock function with given fields: req
func (_m *AuthenticatorHandler) Login(req *authenticationproto.LoginRequest) (*authenticationproto.LoginResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *authenticationproto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*authenticationproto.LoginRequest) (*authenticationproto.LoginResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*authenticationproto.LoginRequest) *authenticationproto.LoginResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authenticationproto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*authenticationproto.LoginRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: req
func (_m *AuthenticatorHandler) Register(req *authenticationproto.RegisterRequest) (*authenticationproto.RegisterResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *authenticationproto.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*authenticationproto.RegisterRequest) (*authenticationproto.RegisterResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*authenticationproto.RegisterRequest) *authenticationproto.RegisterResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authenticationproto.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*authenticationproto.RegisterRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthenticatorHandler creates a new instance of AuthenticatorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticatorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticatorHandler {
	mock := &AuthenticatorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
