// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/sajad-dev/authservice/internal/shared/models"
	mock "github.com/stretchr/testify/mock"
)

// AuthenticatorRepository is an autogenerated mock type for the AuthenticatorRepository type
type AuthenticatorRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: row
func (_m *AuthenticatorRepository) Create(row *models.Accounts) error {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Accounts) error); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: clm, value
func (_m *AuthenticatorRepository) Find(clm string, value string) (*models.Accounts, error) {
	ret := _m.Called(clm, value)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *models.Accounts
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.Accounts, error)); ok {
		return rf(clm, value)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.Accounts); ok {
		r0 = rf(clm, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Accounts)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clm, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthenticatorRepository creates a new instance of AuthenticatorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticatorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticatorRepository {
	mock := &AuthenticatorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
