// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	request "github.com/sajad-dev/authservice/authorization/internal/domain/authorize/dto/request"
	response "github.com/sajad-dev/authservice/authorization/internal/domain/authorize/dto/response"
	mock "github.com/stretchr/testify/mock"
)

// AuthorizeService is an autogenerated mock type for the AuthorizeService type
type AuthorizeService struct {
	mock.Mock
}

// Check provides a mock function with given fields: req
func (_m *AuthorizeService) Check(req request.AuthorizeRequest) (response.AuthorizeResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 response.AuthorizeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.AuthorizeRequest) (response.AuthorizeResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.AuthorizeRequest) response.AuthorizeResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.AuthorizeResponse)
	}

	if rf, ok := ret.Get(1).(func(request.AuthorizeRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthorizeService creates a new instance of AuthorizeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizeService {
	mock := &AuthorizeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
