// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthorizeRepository is an autogenerated mock type for the AuthorizeRepository type
type AuthorizeRepository struct {
	mock.Mock
}

// Check provides a mock function with given fields: sub, obj, act
func (_m *AuthorizeRepository) Check(sub string, obj string, act string) (bool, error) {
	ret := _m.Called(sub, obj, act)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (bool, error)); ok {
		return rf(sub, obj, act)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(sub, obj, act)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(sub, obj, act)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthorizeRepository creates a new instance of AuthorizeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizeRepository {
	mock := &AuthorizeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
