// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: internal/domain/twofactornotifier/twofactornotifier.proto

package twofactornotifierproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TwofactorNotifier_NotifierEmail_FullMethodName = "/twofactornotifierproto.TwofactorNotifier/NotifierEmail"
)

// TwofactorNotifierClient is the client API for TwofactorNotifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TwofactorNotifierClient interface {
	NotifierEmail(ctx context.Context, in *NotifierEmailRequest, opts ...grpc.CallOption) (*TwoFactorNotifierResponse, error)
}

type twofactorNotifierClient struct {
	cc grpc.ClientConnInterface
}

func NewTwofactorNotifierClient(cc grpc.ClientConnInterface) TwofactorNotifierClient {
	return &twofactorNotifierClient{cc}
}

func (c *twofactorNotifierClient) NotifierEmail(ctx context.Context, in *NotifierEmailRequest, opts ...grpc.CallOption) (*TwoFactorNotifierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwoFactorNotifierResponse)
	err := c.cc.Invoke(ctx, TwofactorNotifier_NotifierEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwofactorNotifierServer is the server API for TwofactorNotifier service.
// All implementations must embed UnimplementedTwofactorNotifierServer
// for forward compatibility.
type TwofactorNotifierServer interface {
	NotifierEmail(context.Context, *NotifierEmailRequest) (*TwoFactorNotifierResponse, error)
	mustEmbedUnimplementedTwofactorNotifierServer()
}

// UnimplementedTwofactorNotifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTwofactorNotifierServer struct{}

func (UnimplementedTwofactorNotifierServer) NotifierEmail(context.Context, *NotifierEmailRequest) (*TwoFactorNotifierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifierEmail not implemented")
}
func (UnimplementedTwofactorNotifierServer) mustEmbedUnimplementedTwofactorNotifierServer() {}
func (UnimplementedTwofactorNotifierServer) testEmbeddedByValue()                           {}

// UnsafeTwofactorNotifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwofactorNotifierServer will
// result in compilation errors.
type UnsafeTwofactorNotifierServer interface {
	mustEmbedUnimplementedTwofactorNotifierServer()
}

func RegisterTwofactorNotifierServer(s grpc.ServiceRegistrar, srv TwofactorNotifierServer) {
	// If the following call pancis, it indicates UnimplementedTwofactorNotifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TwofactorNotifier_ServiceDesc, srv)
}

func _TwofactorNotifier_NotifierEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifierEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwofactorNotifierServer).NotifierEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwofactorNotifier_NotifierEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwofactorNotifierServer).NotifierEmail(ctx, req.(*NotifierEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TwofactorNotifier_ServiceDesc is the grpc.ServiceDesc for TwofactorNotifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TwofactorNotifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "twofactornotifierproto.TwofactorNotifier",
	HandlerType: (*TwofactorNotifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifierEmail",
			Handler:    _TwofactorNotifier_NotifierEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/domain/twofactornotifier/twofactornotifier.proto",
}
