// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	twofactorproto "github.com/sajad-dev/authservice/internal/domain/twofactor/twofactorproto"
)

// TwoFactorHandler is an autogenerated mock type for the TwoFactorHandler type
type TwoFactorHandler struct {
	mock.Mock
}

// Email provides a mock function with given fields: req
func (_m *TwoFactorHandler) Email(req *twofactorproto.EmailRequest) (*twofactorproto.TwoFactorResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Email")
	}

	var r0 *twofactorproto.TwoFactorResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*twofactorproto.EmailRequest) (*twofactorproto.TwoFactorResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*twofactorproto.EmailRequest) *twofactorproto.TwoFactorResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twofactorproto.TwoFactorResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*twofactorproto.EmailRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Google provides a mock function with given fields: req
func (_m *TwoFactorHandler) Google(req *twofactorproto.GoogleRequest) (*twofactorproto.TwoFactorResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Google")
	}

	var r0 *twofactorproto.TwoFactorResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*twofactorproto.GoogleRequest) (*twofactorproto.TwoFactorResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*twofactorproto.GoogleRequest) *twofactorproto.TwoFactorResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twofactorproto.TwoFactorResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*twofactorproto.GoogleRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTwoFactorHandler creates a new instance of TwoFactorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTwoFactorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TwoFactorHandler {
	mock := &TwoFactorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
