// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeTwofactoryServer is an autogenerated mock type for the UnsafeTwofactoryServer type
type UnsafeTwofactoryServer struct {
	mock.Mock
}

// mustEmbedUnimplementedTwofactoryServer provides a mock function with no fields
func (_m *UnsafeTwofactoryServer) mustEmbedUnimplementedTwofactoryServer() {
	_m.Called()
}

// NewUnsafeTwofactoryServer creates a new instance of UnsafeTwofactoryServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeTwofactoryServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeTwofactoryServer {
	mock := &UnsafeTwofactoryServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
