// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/shared/errors/errs/grpcerr/errors.proto

package errorsproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_internal_shared_errors_errs_grpcerr_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_errors_errs_grpcerr_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_internal_shared_errors_errs_grpcerr_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_shared_errors_errs_grpcerr_errors_proto protoreflect.FileDescriptor

const file_internal_shared_errors_errs_grpcerr_errors_proto_rawDesc = "" +
	"\n" +
	"0internal/shared/errors/errs/grpcerr/errors.proto\x12\verrorsproto\"'\n" +
	"\vErrorDetail\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB>Z</internal/shared/errors/errs/grpcerr/errorsproto;errorsprotob\x06proto3"

var (
	file_internal_shared_errors_errs_grpcerr_errors_proto_rawDescOnce sync.Once
	file_internal_shared_errors_errs_grpcerr_errors_proto_rawDescData []byte
)

func file_internal_shared_errors_errs_grpcerr_errors_proto_rawDescGZIP() []byte {
	file_internal_shared_errors_errs_grpcerr_errors_proto_rawDescOnce.Do(func() {
		file_internal_shared_errors_errs_grpcerr_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_shared_errors_errs_grpcerr_errors_proto_rawDesc), len(file_internal_shared_errors_errs_grpcerr_errors_proto_rawDesc)))
	})
	return file_internal_shared_errors_errs_grpcerr_errors_proto_rawDescData
}

var file_internal_shared_errors_errs_grpcerr_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_shared_errors_errs_grpcerr_errors_proto_goTypes = []any{
	(*ErrorDetail)(nil), // 0: errorsproto.ErrorDetail
}
var file_internal_shared_errors_errs_grpcerr_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_shared_errors_errs_grpcerr_errors_proto_init() }
func file_internal_shared_errors_errs_grpcerr_errors_proto_init() {
	if File_internal_shared_errors_errs_grpcerr_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_shared_errors_errs_grpcerr_errors_proto_rawDesc), len(file_internal_shared_errors_errs_grpcerr_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_shared_errors_errs_grpcerr_errors_proto_goTypes,
		DependencyIndexes: file_internal_shared_errors_errs_grpcerr_errors_proto_depIdxs,
		MessageInfos:      file_internal_shared_errors_errs_grpcerr_errors_proto_msgTypes,
	}.Build()
	File_internal_shared_errors_errs_grpcerr_errors_proto = out.File
	file_internal_shared_errors_errs_grpcerr_errors_proto_goTypes = nil
	file_internal_shared_errors_errs_grpcerr_errors_proto_depIdxs = nil
}
