// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeTwofactorNotifierServer is an autogenerated mock type for the UnsafeTwofactorNotifierServer type
type UnsafeTwofactorNotifierServer struct {
	mock.Mock
}

// mustEmbedUnimplementedTwofactorNotifierServer provides a mock function with no fields
func (_m *UnsafeTwofactorNotifierServer) mustEmbedUnimplementedTwofactorNotifierServer() {
	_m.Called()
}

// NewUnsafeTwofactorNotifierServer creates a new instance of UnsafeTwofactorNotifierServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeTwofactorNotifierServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeTwofactorNotifierServer {
	mock := &UnsafeTwofactorNotifierServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
