name : "authservice_deploy"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build authentication
      run: cd authentication && go build -o ./build/authservice ./cmd/authentication

    - name: Test authentication
      run: cd authentication && go test -v ./...

    - name: Build authorization
      run: cd authorization && go build -o ./build/authservice ./cmd/authorize
     
    - name: Test authorization
      run: cd authorization && go test -v ./...

    - name: Build XDS
      run: cd getway/xds && go build -o ./build/authservice ./
               
    - name: Test XDS
      run: cd getway/xds && go test -v ./...

